version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodbparcel
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network

  spring-app:
    build: ./  # Replace with the path to your Spring Boot application
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/parcelshops
    depends_on:
      - mongodb
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data:
    driver: local
